version: '3.8'

services:
  sonarqube:
    image: sonarqube:10.7.0-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  sonarqube_data:
  sonarqube_bundled_plugins:
  sonarqube_extensions:
  postgres_data:
